### ISSUE TITLE
Multi-line comment support

### ISSUE THREAD

**Issue by denis-kosovich** [alejandropoveda/atom-language-gsql#5]
https://github.com/alejandropoveda/atom-language-gsql/blob/439d5cccaa68290fe84c76be5b822d75a7c23bf5/grammars/gsql.cson#L225-L261

Hi! Would you mind adding multi-line comment support please? :)
I.e., GSQL supports /* ... */ style comments...

**Comment by alejandropoveda** [comment]
Hello! I am sorry for the late reply.
For sure! Let me get into it and i will try to add this asap.

Greetings!

**Comment by alejandropoveda** [comment]
Hello again Denis,
I just release a new version, v0.6.0, with the multi-line comment support. If you have any issue just let me know.
Thanks!

**Comment by denis-kosovich** [comment]
You're the man!!! 👏 👏 👏 
Thank you very much 😄
